# codegen.py
#
# PyTorch code generator — takes a winning architecture and produces
# clean, runnable, well-commented PyTorch code that anyone can download
# and use immediately.
#
# This is one of the most impressive features of the visualizer.
# Users don't just see which architecture won — they get the actual
# Python file to train it themselves.

from backend.bench.search_space import OPERATIONS, EDGES, get_arch_info


# The full network template — filled in with the winning architecture's
# specific operations at export time.
_TEMPLATE = '''"""
NAS-Visualizer — Generated Architecture
========================================
Architecture index : {arch_index}
Architecture string: {arch_string}
Operations         : {operations}
Validation accuracy: {val_accuracy:.2f}%  (20-epoch run on CIFAR-10)
Extrapolated acc.  : {extrapolated:.2f}%  (estimated 200-epoch)
Parameters         : {params:,}
FLOPs              : {flops:.2f} M

Generated by NAS-Visualizer — github.com/{github_user}/nas-visualizer
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# -----------------------------------------------------------------------
# Building blocks
# -----------------------------------------------------------------------

class ConvBnRelu(nn.Module):
    """Convolution → BatchNorm → ReLU. Standard vision building block."""

    def __init__(self, in_ch, out_ch, kernel, stride=1, padding=0):
        super().__init__()
        self.op = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel,
                      stride=stride, padding=padding, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.op(x)


class CellOp(nn.Module):
    """One operation on one edge of the cell DAG."""

    def __init__(self, op_name: str, channels: int):
        super().__init__()
        self.op_name = op_name

        ops = {{
            'none':         lambda: None,
            'skip_connect': nn.Identity,
            'nor_conv_1x1': lambda: ConvBnRelu(channels, channels, 1, padding=0),
            'nor_conv_3x3': lambda: ConvBnRelu(channels, channels, 3, padding=1),
            'avg_pool_3x3': lambda: nn.AvgPool2d(3, stride=1, padding=1),
        }}
        self.op = ops[op_name]()

    def forward(self, x):
        if self.op is None:
            return torch.zeros_like(x)
        return self.op(x)


class NASCell(nn.Module):
    """
    The searched cell — a DAG with 4 nodes and 6 directed edges.

    Topology:
        Node 0 (input)  →  Node 1, 2, 3
        Node 1          →  Node 2, 3
        Node 2          →  Node 3 (output)

    Each node sums all incoming edge outputs.
    Operations per edge:
{edge_comments}
    """

    EDGES = {edges}

    def __init__(self, channels: int):
        super().__init__()
        operations = {op_list}
        self.ops   = nn.ModuleList([
            CellOp(op, channels) for op in operations
        ])

    def forward(self, x):
        nodes = [None] * 4
        nodes[0] = x

        for i, (src, tgt) in enumerate(self.EDGES):
            out = self.ops[i](nodes[src])
            nodes[tgt] = out if nodes[tgt] is None else nodes[tgt] + out

        return nodes[3] if nodes[3] is not None else torch.zeros_like(x)


class NASNetwork(nn.Module):
    """
    Full network: stem → 3 stages of NASCells → classifier.
    Faithful to the NAS-Bench-201 macro skeleton.
    """

    def __init__(self, num_classes: int = 10, channels: int = 16,
                 cells_per_stage: int = 3):
        super().__init__()

        self.stem = ConvBnRelu(3, channels, 3, padding=1)

        self.stage1 = nn.Sequential(*[NASCell(channels) for _ in range(cells_per_stage)])
        self.down1  = ConvBnRelu(channels, channels * 2, 3, stride=2, padding=1)

        self.stage2 = nn.Sequential(*[NASCell(channels * 2) for _ in range(cells_per_stage)])
        self.down2  = ConvBnRelu(channels * 2, channels * 4, 3, stride=2, padding=1)

        self.stage3 = nn.Sequential(*[NASCell(channels * 4) for _ in range(cells_per_stage)])

        self.gap        = nn.AdaptiveAvgPool2d(1)
        self.classifier = nn.Linear(channels * 4, num_classes)

    def forward(self, x):
        x = self.stem(x)
        x = self.stage1(x)
        x = self.down1(x)
        x = self.stage2(x)
        x = self.down2(x)
        x = self.stage3(x)
        x = self.gap(x).view(x.size(0), -1)
        return self.classifier(x)


# -----------------------------------------------------------------------
# Training script
# -----------------------------------------------------------------------

def get_loaders(batch_size=64):
    import torchvision
    import torchvision.transforms as T

    mean, std = (0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616)

    train_tf = T.Compose([
        T.RandomCrop(32, padding=4),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
        T.Normalize(mean, std),
    ])
    val_tf = T.Compose([T.ToTensor(), T.Normalize(mean, std)])

    train = torchvision.datasets.CIFAR10('.', train=True,  download=True, transform=train_tf)
    val   = torchvision.datasets.CIFAR10('.', train=False, download=True, transform=val_tf)

    return (
        torch.utils.data.DataLoader(train, batch_size=batch_size, shuffle=True,  num_workers=2),
        torch.utils.data.DataLoader(val,   batch_size=batch_size, shuffle=False, num_workers=2),
    )


def train(epochs=200, lr=0.1):
    device       = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model        = NASNetwork().to(device)
    optimizer    = torch.optim.SGD(model.parameters(), lr=lr,
                                   momentum=0.9, weight_decay=5e-4, nesterov=True)
    scheduler    = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    criterion    = nn.CrossEntropyLoss()
    train_loader, val_loader = get_loaders()

    print(f"Training on {{device}} for {{epochs}} epochs")
    print(f"Parameters: {{sum(p.numel() for p in model.parameters()):,}}")

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(inputs), labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            total_loss += loss.item()

        scheduler.step()

        if epoch % 10 == 0 or epoch == epochs:
            model.eval()
            correct = total = 0
            with torch.no_grad():
                for inputs, labels in val_loader:
                    inputs, labels = inputs.to(device), labels.to(device)
                    correct += model(inputs).argmax(1).eq(labels).sum().item()
                    total   += labels.size(0)
            print(f"Epoch {{epoch:3d}} | loss {{total_loss/len(train_loader):.4f}} "
                  f"| val acc {{100*correct/total:.2f}}%")

    return model


if __name__ == '__main__':
    model = train(epochs=200)
    torch.save(model.state_dict(), 'nas_best_model.pth')
    print("Model saved to nas_best_model.pth")
'''


def generate_code(
    arch_index: int,
    val_accuracy: float = 0.0,
    extrapolated: float = 0.0,
    params: int = 0,
    flops: float = 0.0,
    github_user: str = 'danielomoteshohacks',
) -> str:
    """
    Generate a complete, runnable PyTorch file for the given architecture.

    Every field in the template is filled in with real values from
    the search results. The output is a .py file the user can run
    directly to train the discovered architecture to convergence.
    """
    arch    = get_arch_info(arch_index)
    ops     = arch['operations']
    edges   = arch['edges']

    # Build the human-readable edge comments for the docstring
    edge_comments = '\n'.join(
        f'        Edge {e["edge_index"]} (node {e["source"]} → node {e["target"]})'
        f': {e["operation"]}'
        for e in edges
    )

    return _TEMPLATE.format(
        arch_index     = arch_index,
        arch_string    = arch['arch_string'],
        operations     = ops,
        val_accuracy   = val_accuracy,
        extrapolated   = extrapolated,
        params         = params,
        flops          = flops,
        github_user    = github_user,
        edge_comments  = edge_comments,
        edges          = repr(EDGES),
        op_list        = repr(ops),
    )